project:
  type: website

website:
  title: "CMV Simulation"
  sidebar:
    style: docked
    search: false
    contents:
      - href: index.qmd
        text: Home
      - href: GenerateBaselineData.qmd
        text: Generate Baseline Data
    tools:
      - icon: github
        href: https://github.com/twitched/cmv-ier-sim
      

format:
  html:
    theme: 
      - cosmo 
      - custom.scss    
    css: styles.css
    toc: true
    page-layout: full
    monofont: "Fira Code"
    df-print: paged
    link-citations: true
    code-fold: true
    code-tools: true
    html-math-method: katex
    repo-url: https://github.com/twitched/cmv-ier-sim
    repo-text: "GitHub"