project:
  type: website

website:
  title: "CMV Simulation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - GenerateBaselineData.qmd
      

format:
  html:
    theme: 
      - cosmo 
      - custom.scss    
    css: styles.css
    toc: true
    page-layout: full
    monofont: "Fira Code"
    df-print: paged
    link-citations: true
    code-fold: true
    code-tools: true
